const columns = [
    {name: "ID", uid: "id", sortable: true},
    {name: "NAME", uid: "name", sortable: true},
    {name: "AGE", uid: "age", sortable: true},
    {name: "ROLE", uid: "role", sortable: true},
    {name: "TEAM", uid: "team"},
    {name: "EMAIL", uid: "email"},
    {name: "STATUS", uid: "status", sortable: true},
    {name: "ACTIONS", uid: "actions"},
  ];
  
  const statusOptions = [
    {name: "Active", uid: "active"},
    {name: "Paused", uid: "paused"},
    {name: "Vacation", uid: "vacation"},
  ];
  
  const users = [
    {
      id: 1,
      name: "Antonio Rivera",
      role: "Director Médico",
      team: "Administración Hospitalaria",
      status: "active",
      age: "29",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
      email: "antonio.rivera@example.com",
    },
    {
      id: 2,
      name: "Sofía Martínez",
      role: "Líder de Enfermería",
      team: "Enfermería",
      status: "paused",
      age: "25",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
      email: "sofia.martinez@example.com",
    },
    {
      id: 3,
      name: "Juanita Pérez",
      role: "Médico Senior",
      team: "Medicina General",
      status: "active",
      age: "22",
      avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
      email: "juanita.perez@example.com",
    },
    {
      id: 4,
      name: "Guillermo Hernández",
      role: "Coordinador de Mercadotecnia",
      team: "Mercadotecnia Hospitalaria",
      status: "vacation",
      age: "28",
      avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
      email: "guillermo.hernandez@example.com",
    },
    {
      id: 5,
      name: "Cristina López",
      role: "Supervisora de Ventas",
      team: "Gestión de Pacientes",
      status: "active",
      age: "24",
      avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
      email: "cristina.lopez@example.com",
    },
    {
      id: 6,
      name: "Roberto Jiménez",
      role: "Gerente de Proyectos",
      team: "Administración Hospitalaria",
      age: "29",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
      email: "roberto.jimenez@example.com",
      status: "Active",
    },
    {
      id: 7,
      name: "Miguel Ángel Torres",
      role: "Especialista en Diseño",
      team: "Diseño de Interiores Hospitalarios",
      status: "paused",
      age: "27",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
      email: "miguelangel.torres@example.com",
    },
    {
      id: 8,
      name: "Samantha Gómez",
      role: "Gerente de Recursos Humanos",
      team: "Recursos Humanos",
      status: "active",
      age: "31",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
      email: "samantha.gomez@example.com",
    },
    {
      id: 9,
      name: "Francisco Díaz",
      role: "Gerente Financiero",
      team: "Finanzas Hospitalarias",
      status: "vacation",
      age: "33",
      avatar: "https://i.pravatar.cc/150?img=4",
      email: "francisco.diaz@example.com",
    },
    {
      id: 10,
      name: "Emilia Castillo",
      role: "Gerente de Operaciones",
      team: "Operaciones Hospitalarias",
      status: "active",
      age: "35",
      avatar: "https://i.pravatar.cc/150?img=5",
      email: "emilia.castillo@example.com",
    },
    {
      id: 11,
      name: "Carlos Navarro",
      role: "Médico Junior",
      team: "Medicina General",
      status: "active",
      age: "22",
      avatar: "https://i.pravatar.cc/150?img=8",
      email: "carlos.navarro@example.com",
    },
    {
      id: 12,
      name: "Mónica Ruiz",
      role: "Gerente de Producto",
      team: "Farmacia Hospitalaria",
      status: "paused",
      age: "28",
      avatar: "https://i.pravatar.cc/150?img=10",
      email: "monica.ruiz@example.com",
    },
    {
      id: 13,
      name: "Oscar Vega",
      role: "Supervisor de Seguridad",
      team: "Seguridad Hospitalaria",
      status: "active",
      age: "37",
      avatar: "https://i.pravatar.cc/150?img=12",
      email: "oscar.vega@example.com",
    },
    {
      id: 14,
      name: "Graciela Morales",
      role: "Especialista en Mercadotecnia",
      team: "Mercadotecnia Hospitalaria",
      status: "active",
      age: "30",
      avatar: "https://i.pravatar.cc/150?img=16",
      email: "graciela.morales@example.com",
    },
    {
      id: 15,
      name: "Noé Cárdenas",
      role: "Especialista en TI",
      team: "Tecnologías de la Información",
      status: "paused",
      age: "31",
      avatar: "https://i.pravatar.cc/150?img=15",
      email: "noe.cardenas@example.com",
    },
    {
      id: 16,
      name: "Valeria Ponce",
      role: "Gerente",
      team: "Gestión de Pacientes",
      status: "active",
      age: "29",
      avatar: "https://i.pravatar.cc/150?img=20",
      email: "valeria.ponce@example.com",
    },
    {
      id: 17,
      name: "Luis Alberto Fernández",
      role: "Analista de Datos",
      team: "Investigación y Desarrollo",
      status: "active",
      age: "28",
      avatar: "https://i.pravatar.cc/150?img=33",
      email: "luisalberto.fernandez@example.com",
    },
  ];
  
  export {columns, users, statusOptions};
  